# Generated by Django 4.2.5 on 2023-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userdetail_phone_userdetail_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='addess',
            new_name='address',
        ),
    ]
