# Generated by Django 4.2.5 on 2023-09-26 12:08

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_addess_userdetail_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Please select a drink type'), ('A', 'Americano'), ('C', 'Cappuccino'), ('CB', 'Colld Brew Coffee')], max_length=10)),
                ('size', models.CharField(choices=[(None, 'Please select a size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(max_length=200, validators=[shop.validators.vaidate_address]),
        ),
    ]
