# Generated by Django 4.2.5 on 2023-09-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coffe_alter_userdetail_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffe',
            new_name='Coffee',
        ),
    ]
